### ISSUE TITLE
展开全部 导致获取简介信息不完整

### ISSUE THREAD

**Issue by phrack2561** [fugary/simple-boot-douban-api#4]
get_meta获取书籍简介的时候，由于文本内容过长，最后会出现展开全部的按钮，目前是直接拷贝了展开全部，是否可以完善以获取全部简介内容

**Comment by watermoonchandra** [comment]
我也发现这个问题。补充一句，不能获取网页原格式，段落会合并在一起，成为一连串纯文本，不便于阅读。
