### ISSUE TITLE
修改calibre-web无效

### ISSUE THREAD

**Issue by liushawulan** [fugary/simple-boot-douban-api#6]
浏览器可以，但是calibre-web依然搜索不到douban. get_meta.js修改成了NAS的IP。
怎么回事呢？docker也开启了该容器。

**Comment by fugary** [comment]
还有可能是浏览器缓存，浏览器一般会缓存js，建议清理浏览器缓存再次尝试

**Comment by fugary** [comment]
注意/calibre-web/app/cps/static/js/get_meta.js文件路径是technosoft2000/calibre-web镜像的路径，如果使用的是linuxserver/calibre-web，路径是 /app/calibre-web/cps/static/js/get_meta.js

**Comment by liushawulan** [comment]
老哥，可以用了，我总结下步骤：首先正确的路径，其次，nas中添加反向代理，我的一定要https, 可能linuxserver/calibre-web是https的，放置了ssl证书在书库中，在get-meta.js中 var douban="https://nas-ip:xxx"，可能和书库自身有没有开启https有关。
谢谢老哥。：）
