### ISSUE TITLE
新版的calibre-web已经修改了元数据的配置，能弄个教程吗，我加进去的都是搜索错误

### ISSUE THREAD

**Issue by dandelions** [fugary/simple-boot-douban-api#7]
新版的calibre-web已经修改了元数据的配置，能弄个教程吗，我加进去的都是搜索错误
路径在  calibre-web/app/cps/metadate_provider

import requests
from cps.services.Metadata import Metadata

class Douban(Metadata):
    __name__ = "Douban"
    __id__ = "douban"

    def search(self, query, __):
        if self.active:
            val = list()
            result = requests.get("http://192.168.2.16:8085/v2/book/search?q="+query.replace(" ","+"))
            for r in result.json()['books']:
                v = dict()
                v['id'] = r['id']
                v['title'] = r['title']
                v['authors'] = r.get('author', [])
                v['description'] = r['summary']
                v['publisher'] = r['publisher']
                v['publishedDate'] = r['pubdate']
                v['tags'] = r['series'].get('title', "")
                v['rating'] = r['rating'].get('average', 0)
                v['cover'] = r['image']
                v['source'] = {
                    "id": self.__id__,
                    "description": "Douban Books",
                    "link": "http://192.168.2.16:8085/v2/book/"}
                v['url'] = "https://book.douban.com/subject/" + r['id']+"/"
                val.append(v)
            return val

**Comment by fugary** [comment]
新版本还没有正式发布，建议先使用0.6.13版本，新版有空看看是否能支持

**Comment by fugary** [comment]
新版本：https://github.com/fugary/calibre-web-douban-api
